apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-app
  namespace: inventory
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-app
  template:
    metadata:
      labels:
        app: inventory-app
    spec:
      containers:
        - name: inventory-app
          image: abunahim/inventory-management:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: inventory-config
                  key: DB_NAME
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: inventory-config
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: inventory-secret
                  key: DB_PASSWORD
          readinessProbe:
            httpGet:
              path: /products
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /products
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15